// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN12U-NPVPQVIvdqNhXDSgj8AsRUJm-nI',
    appId: '1:879958752713:web:8003695bce0ec7c5e83c18',
    messagingSenderId: '879958752713',
    projectId: 'budi-rahayu-care',
    authDomain: 'budi-rahayu-care.firebaseapp.com',
    storageBucket: 'budi-rahayu-care.firebasestorage.app',
    measurementId: 'G-TE9NL530T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDpXV6PWGhAGXhHTtgdANhMaG3oOVF2o',
    appId: '1:879958752713:android:773b69276370cbd5e83c18',
    messagingSenderId: '879958752713',
    projectId: 'budi-rahayu-care',
    storageBucket: 'budi-rahayu-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgVPZRQKEr7UolwIrcsEJi9X1q6qSxts',
    appId: '1:879958752713:ios:cd51fe7be0e119fbe83c18',
    messagingSenderId: '879958752713',
    projectId: 'budi-rahayu-care',
    storageBucket: 'budi-rahayu-care.firebasestorage.app',
    iosBundleId: 'com.example.budiRahayuCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgVPZRQKEr7UolwIrcsEJi9X1q6qSxts',
    appId: '1:879958752713:ios:cd51fe7be0e119fbe83c18',
    messagingSenderId: '879958752713',
    projectId: 'budi-rahayu-care',
    storageBucket: 'budi-rahayu-care.firebasestorage.app',
    iosBundleId: 'com.example.budiRahayuCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN12U-NPVPQVIvdqNhXDSgj8AsRUJm-nI',
    appId: '1:879958752713:web:8fe3f358a2bf3823e83c18',
    messagingSenderId: '879958752713',
    projectId: 'budi-rahayu-care',
    authDomain: 'budi-rahayu-care.firebaseapp.com',
    storageBucket: 'budi-rahayu-care.firebasestorage.app',
    measurementId: 'G-LBPHK4WMDB',
  );
}
